---
- hosts: localhost
  user: <username>
  become: yes
  vars:
    jenkins_home: /var/lib/jenkins
    jenkins_local: /opt/jenkins
    image: myjenkins
    password: foobar
    sock: /var/run/docker.sock
    docker: /usr/bin/docker
    sysconfig: /etc/sysconfig/docker
    uid: 1000
    port: 9191
  tasks:
    - name: clean up docker
      ignore_errors: yes
      shell: |
        docker stop $(docker ps -a -q)
        docker rm -f $(docker ps -a -q)
        docker rmi -f $(docker images -q)
      args:
        warn: no

    - name: Create jenkins directory beforehand
      file: path={{ jenkins_local }} state=directory owner={{uid}} mode=0755

    - name: Build a local jenkins docker container
      shell: |
        docker build -t {{image}} .
      args:
        warn: no

    # port 9191 needs to be opened by cloud server tools beforehand
    - name: insert firewalld rule
      firewalld: port={{port}}/tcp permanent=true state=enabled immediate=yes

    - name: Run jenkins docker daemon at port 9191
      shell: |
        docker run -u {{uid}} -e JENKINS_PASSWORD={{password}} -p {{port}}:8080 -p 50000:50000 -v {{sock}}:{{sock}}:z -v {{docker}}:{{docker}} -v {{sysconfig}}:{{sysconfig}}:z -v {{jenkins_local}}:{{jenkins_home}}:z -d myjenkins
      args:
        warn: no

